#!/bin/bash



mkdir -p '/'
cat << EOF | base64 -d > '/path'
Y29udGVudA==
EOF




if grep -q 'resolvConf: /etc/resolv.conf' /var/lib/kubelet/config/kubelet; then
  sed -i -e 's|resolvConf: /etc/resolv.conf|resolvConf: /run/systemd/resolve/resolv.conf|g' /var/lib/kubelet/config/kubelet;
fi
