apiVersion: apps/v1
kind: Deployment
metadata:
  name: gardener-extension-os-ubuntu
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-os-ubuntu
    helm.sh/chart: gardener-extension-os-ubuntu
    app.kubernetes.io/instance: {{ .Release.Name }}
    high-availability-config.resources.gardener.cloud/type: controller
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gardener-extension-os-ubuntu
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- if and .Values.metrics.enableScraping }}
      annotations:
        prometheus.io/name: "{{ .Release.Name }}"
        prometheus.io/scrape: "true"
        # default metrics endpoint in controller-runtime
        prometheus.io/port: "{{ .Values.metrics.port }}"
      {{- end }}
      labels:
        app.kubernetes.io/name: gardener-extension-os-ubuntu
        app.kubernetes.io/instance: {{ .Release.Name }}
        networking.gardener.cloud/to-runtime-apiserver: allowed
        networking.gardener.cloud/to-dns: allowed
    spec:
      priorityClassName: gardener-system-900
      serviceAccountName: gardener-extension-os-ubuntu
      containers:
      - name: gardener-extension-os-ubuntu
        image: {{ include "image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /gardener-extension-os-ubuntu
        - --max-concurrent-reconciles={{ .Values.controllers.concurrentSyncs }}
        - --disable-controllers={{ .Values.disableControllers | join "," }}
        - --heartbeat-namespace={{ .Release.Namespace }} 
        - --heartbeat-renew-interval-seconds={{ .Values.controllers.heartbeat.renewIntervalSeconds }} 
        - --ignore-operation-annotation={{ .Values.controllers.ignoreOperationAnnotation }}
        - --gardener-version={{ .Values.gardener.version }}
        - --metrics-bind-address=:{{ .Values.metrics.port }}
        - --disable-unattended-upgrades={{ .Values.disableAutoUpgrades }}
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | nindent 10 }}
{{- end }}
