apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ubuntu.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ubuntu.labels" . | nindent 4 }}
    high-availability-config.resources.gardener.cloud/type: controller
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ubuntu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if and .Values.metrics.enableScraping }}
      annotations:
        checksum/config: {{ include "ubuntu.configChecksum" . }}
        prometheus.io/name: "{{ .Release.Name }}"
        prometheus.io/scrape: "true"
        # default metrics endpoint in controller-runtime
        prometheus.io/port: "{{ .Values.metrics.port }}"
      {{- end }}
      labels:
        {{- include "ubuntu.labels" . | nindent 8 }}
        networking.gardener.cloud/to-runtime-apiserver: allowed
        networking.gardener.cloud/to-dns: allowed
    spec:
      priorityClassName: gardener-system-900
      serviceAccountName: {{ include "ubuntu.name" . }}
      containers:
      - name: gardener-extension-os-ubuntu
        image: {{ include "image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /gardener-extension-os-ubuntu
        - --max-concurrent-reconciles={{ .Values.controllers.concurrentSyncs }}
        - --disable-controllers={{ .Values.disableControllers | join "," }}
        - --heartbeat-namespace={{ .Release.Namespace }} 
        - --heartbeat-renew-interval-seconds={{ .Values.controllers.heartbeat.renewIntervalSeconds }}
        - --config=/config/config.yaml
        - --ignore-operation-annotation={{ .Values.controllers.ignoreOperationAnnotation }}
        - --gardener-version={{ .Values.gardener.version }}
        - --metrics-bind-address=:{{ .Values.metrics.port }}
        - --disable-unattended-upgrades={{ .Values.disableAutoUpgrades }}
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | nindent 10 }}
{{- end }}
        volumeMounts:
          - name: config
            mountPath: /config
            readOnly: true
      volumes:
        - name: config
          secret:
            secretName: {{ include "ubuntu.name" . }}-config
            defaultMode: 420
