apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ubuntu.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ubuntu.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "ubuntu.selectorLabels" . | nindent 6}}
{{- if semverCompare ">= 1.26-0" .Capabilities.KubeVersion.Version }}
  unhealthyPodEvictionPolicy: AlwaysAllow
{{- end }}
