apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ubuntu.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ubuntu.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}