apiVersion: v1
kind: Service
metadata:
  name: {{ include "ubuntu.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    networking.resources.gardener.cloud/from-all-seed-scrape-targets-allowed-ports: '[{"port":{{ .Values.metrics.port }},"protocol":"TCP"}]'
    networking.resources.gardener.cloud/namespace-selectors: '[{"matchLabels":{"kubernetes.io/metadata.name":"garden"}}]'
    networking.resources.gardener.cloud/pod-label-selector-namespace-alias: extensions
  labels:
    {{- include "ubuntu.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "ubuntu.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    protocol: TCP
