apiVersion: v1
kind: ServiceAccount
metadata:
  name: gardener-extension-os-ubuntu
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-os-ubuntu
    helm.sh/chart: gardener-extension-os-ubuntu
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if ne .Values.gardener.version "" }}
{{- if semverCompare ">= 1.37-0" .Values.gardener.version }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
