{{- if .Values.vpa.enabled}}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "ubuntu.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ubuntu.labels" . | nindent 4 }}
spec:
  {{- if .Values.vpa.resourcePolicy }}
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          memory: {{ required "vpa.resourcePolicy.minAllowed.memory is required" .Values.vpa.resourcePolicy.minAllowed.memory }}
  {{- end }}
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ubuntu.name" . }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updatePolicy.updateMode }}
{{- end }}